<a href="https://colab.research.google.com/github/taimur1871/Coursera_Capstone/blob/master/Clean_Crime_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [0]:
#analyzing crime data, this data is taken from Denver government website
df_crime = pd.read_csv('crime.csv')
# deleting unwanted columns
df_crime.drop(['INCIDENT_ID', 'OFFENSE_CODE', 'OFFENSE_CODE_EXTENSION', 'FIRST_OCCURRENCE_DATE', 'LAST_OCCURRENCE_DATE', 'GEO_X', 'GEO_Y', 'DISTRICT_ID'], axis=1, inplace=True)
df_crime.dropna(axis = 0, how = 'any', subset=['GEO_LON', 'GEO_LAT'], inplace=True)
df_crime.head()

          OFFENSE_ID                 OFFENSE_TYPE_ID  ... IS_CRIME IS_TRAFFIC
0   2018869789239900                     theft-other  ...        1          0
1   2015664356544100                traffic-accident  ...        0          1
2  20176005213239901                   theft-bicycle  ...        1          0
3  20196012240230800                 theft-from-bldg  ...        1          0
4   2018861883501600  violation-of-restraining-order  ...        1          0

[5 rows x 11 columns]

In [0]:
# cleaning out traffic related violations
df_crime1 = df_crime[df_crime.IS_TRAFFIC == 0]

          OFFENSE_ID                 OFFENSE_TYPE_ID  ... IS_CRIME IS_TRAFFIC
0   2018869789239900                     theft-other  ...        1          0
2  20176005213239901                   theft-bicycle  ...        1          0
3  20196012240230800                 theft-from-bldg  ...        1          0
4   2018861883501600  violation-of-restraining-order  ...        1          0
5   2018264446131600               threats-to-injure  ...        1          0

[5 rows x 11 columns]

In [0]:
# removing crime type column as the non criminal events have been removed
df_crime1.drop(['IS_CRIME'], axis = 1, inplace = True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

0     12/27/2018 4:51:00 PM
2      6/12/2017 8:44:00 AM
3      12/9/2019 1:35:00 PM
4    12/22/2018 10:00:00 PM
5      4/20/2018 1:33:00 PM
Name: REPORTED_DATE, dtype: object

In [0]:
# removing crime data prior to 2019, this leaves a much smaller and more relevant dataset
temp = df_crime1['REPORTED_DATE']
pd.to_datetime(temp, yearfirst=True, infer_datetime_format=True)
temp = temp.str.split(pat = ' ', expand=True)
temp1 = temp[0]
temp1 = pd.to_datetime(temp1)
df_crime1['year'] = temp1

df_crime2 = df_crime1[df_crime1.year > pd.to_datetime('2018-12-31')]
df_crime2

               OFFENSE_ID  ...       year
3       20196012240230800  ... 2019-12-09
13       2019738697239900  ... 2019-11-20
15        201985551220300  ... 2019-02-07
20       2020131877570700  ... 2020-02-29
38       2019126652570700  ... 2019-02-26
...                   ...  ...        ...
483844  20206004761239900  ... 2020-04-28
483846   2020272284240400  ... 2020-05-04
483847   2020242622299901  ... 2020-04-22
483848   2020246575501601  ... 2020-04-23
483849  20206004556230500  ... 2020-04-23

[87105 rows x 10 columns]